services:
  web:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.server.dev
    ports:
      - "5001:80"
    env_file:
      - scripts/setup_env.sh

    command: "uvicorn aero.main:app --host 0.0.0.0 --port 80"

    volumes:
      - ./aero:/app/aero
      - ./data:/app/aero/data
    depends_on:
        - database

  database:
    restart: always
    image: postgres:17.4
    env_file:
      - scripts/setup_env.sh
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=osprey_development
    ports:
      - "5432:5432"
    volumes:
      - osprey-postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  osprey-postgres-data:
    external: true
