name: ${PROJECT_NAME}

services:
  web:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.server.dev

    # ports:
    #  - "8000:80"

    env_file:
      - ${SETUP_ENV_SH}

    # expose:
    #  - 8081

    command: "uvicorn aero.main:app --host 0.0.0.0  --port 8081 ${ROOT_PATH_ARG:-}"
    # --host 0.0.0.0  --port 8081 --proxy-headers --forwarded-allow-ips *"
    # --ssl-keyfile=/keys/cels.anl.gov-key.pem --ssl-certfile=/certs/cels-incommon.anl.gov-bundle.pem"
    # --proxy-headers --uds /var/sockets/uvicorn.sock"

    volumes:
      - ./aero:/app/aero
      - ./data:/app/aero/data
      # - /etc/pki/tls/private:/keys
      # - /etc/pki/tls/certs:/certs
    depends_on:
      - database
    networks:
      default: {}
      aero-shared:
        aliases:
          - ${WEB_ALIAS:-web}

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/pki/tls/private:/keys
      - /etc/pki/tls/certs:/certs
      - ./nginx/aero-app.conf:/etc/nginx/conf.d/aero-app.conf

    depends_on:
      - web
    networks:
      - default
      - aero-shared

  database:
    restart: always
    image: postgres:17.4
    env_file:
      - ${SETUP_ENV_SH}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      default: {}
      aero-shared:
        aliases:
          - ${ADMINER_ALIAS:-adminer}

volumes:
  pgdata:
    external: true
    name: ${PG_VOLUME:-osprey-postgres-data}

networks:
  aero-shared:
    external: true
    name: aero-shared
