services:
  web:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.server.dev
    ports:
      - "5001:80"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=dsaas-postgres-database-1 # NOTE: Make sure it is the same as the database-name
      - DATABASE_NAME=osprey_development
      - PORTAL_CLIENT_ID=${PORTAL_CLIENT_ID}
      - PORTAL_CLIENT_SECRET=${PORTAL_CLIENT_SECRET}
      - GLOBUS_CLI_CLIENT_ID=${PORTAL_CLIENT_ID}
      - GLOBUS_CLI_CLIENT_SECRET=${PORTAL_CLIENT_SECRET}
      - GLOBUS_COMPUTE_CLIENT_ID=${PORTAL_CLIENT_ID}
      - GLOBUS_COMPUTE_CLIENT_SECRET=${PORTAL_CLIENT_SECRET}
      - FLASK_APP=app/run.py

      # Project owner registers this
      - GLOBUS_FLOW_DOWNLOAD_FUNCTION=599bbfb3-8952-40ae-95f3-414d8470b30e
      - GLOBUS_FLOW_COMMIT_FUNCTION=8936eda3-c6f9-4830-a5d0-6b85d620ac00
      - GLOBUS_FLOW_ANALYSIS_VERSION_FUNCTION=4d69c659-fa2f-42ab-87d2-c7b9a65ca975
      - GLOBUS_FLOW_ANALYSIS_COMMIT_FUNCTION=b2223790-1e4b-4a18-9a68-1d020f52ad43
      - SEARCH_INDEX=9b130f83-3598-46b7-838a-f68ebe92c6eb
      # For timer email
      - DSAAS_EMAIL_PASSWORD=${DSAAS_EMAIL_PASSWORD}

    volumes:
      - ./aero:/app/aero
      - ./data:/app/aero/data
    depends_on:
        - postgres-database

  postgres-database:
    restart: always
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=osprey_development
    ports:
      - "5432:5432"
    volumes:
      - osprey-postgres-data:/var/lib/postgresql/data
volumes:
  osprey-postgres-data:
    external: true
