"""Add hash column in flows

Revision ID: 134ba9368422
Revises: 5069547881ea
Create Date: 2024-09-23 11:46:16.212130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "134ba9368422"
down_revision = "5069547881ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.add_column(sa.Column("arg_hash", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.drop_column("arg_hash")

    # ### end Alembic commands ###
