"""added filename to output

Revision ID: 4e2a3f5f194e
Revises: cfdd69365e30
Create Date: 2023-12-01 04:04:37.941072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e2a3f5f194e"
down_revision = "cfdd69365e30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.add_column(sa.Column("filename", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.drop_column("filename")

    # ### end Alembic commands ###
