"""fix bug in migrations

Revision ID: 5069547881ea
Revises: 0a81442faea4
Create Date: 2024-09-23 03:09:38.301450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5069547881ea"
down_revision = "0a81442faea4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provenance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provenance_id"), ["id"], unique=False)

    op.create_table(
        "provenance_contribution",
        sa.Column("prov_id", sa.Uuid(), nullable=True),
        sa.Column("produced_version_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["produced_version_id"],
            ["data_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prov_id"],
            ["provenance.id"],
        ),
    )
    op.create_table(
        "provenance_derivation",
        sa.Column("prov_id", sa.Uuid(), nullable=True),
        sa.Column("derived_version_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["derived_version_id"],
            ["data_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prov_id"],
            ["provenance.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provenance_derivation")
    op.drop_table("provenance_contribution")
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provenance_id"))

    op.drop_table("provenance")
    # ### end Alembic commands ###
