"""Adding Provenance & Function

Revision ID: 6bef5eae159c
Revises: f7cce118e24f
Create Date: 2023-06-26 18:37:16.040610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bef5eae159c"
down_revision = "f7cce118e24f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "function",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("function")
    # ### end Alembic commands ###
