"""updates to provenance including policies

Revision ID: 798a339a9ec1
Revises: 354a7ed3a6ac
Create Date: 2024-06-26 21:44:20.971676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "798a339a9ec1"
down_revision = "354a7ed3a6ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("policy", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_executed", sa.Date(), nullable=True))

    with op.batch_alter_table("provenance_derivation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("previous_source_id", sa.Integer(), nullable=True)
        )
        batch_op.drop_constraint(
            "provenance_derivation_previous_source_version_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "source", ["previous_source_id"], ["id"])
        batch_op.drop_column("previous_source_version_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provenance_derivation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "previous_source_version_id",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "provenance_derivation_previous_source_version_id_fkey",
            "source_version",
            ["previous_source_version_id"],
            ["id"],
        )
        batch_op.drop_column("previous_source_id")

    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.drop_column("last_executed")
        batch_op.drop_column("policy")

    # ### end Alembic commands ###
