"""Include GCS server location in source_files

Revision ID: 96951d255960
Revises: a4b17797b8de
Create Date: 2024-05-06 14:51:09.127180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96951d255960"
down_revision = "a4b17797b8de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gcs_domain", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("gcs_uuid", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_file", schema=None) as batch_op:
        batch_op.drop_column("gcs_uuid")
        batch_op.drop_column("gcs_domain")

    # ### end Alembic commands ###
