"""add size column to file table

Revision ID: b2d49a4da3c2
Revises: 1bbe11e1fd70
Create Date: 2024-01-16 22:45:08.151170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2d49a4da3c2"
down_revision = "1bbe11e1fd70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("size", sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_file", schema=None) as batch_op:
        batch_op.drop_column("size")

    # ### end Alembic commands ###
