"""update provenance capture

Revision ID: cfdd69365e30
Revises: 050e9ef7f692
Create Date: 2023-11-28 17:11:03.449561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfdd69365e30"
down_revision = "050e9ef7f692"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("function_args", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.drop_column("description")
        batch_op.drop_column("function_args")

    # ### end Alembic commands ###
