FROM --platform=linux/x86_64 ubuntu:20.04
RUN apt update
RUN apt install -y gnupg curl
RUN curl -LOs https://downloads.globus.org/globus-connect-server/stable/installers/repo/deb/globus-repo_latest_all.deb
RUN dpkg -i globus-repo_latest_all.deb
RUN apt-key add /usr/share/globus-repo/RPM-GPG-KEY-Globus
RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y globus-connect-server54