FROM python:3.10
WORKDIR /app
COPY osprey/server/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
RUN pip install -e .
WORKDIR /app/osprey/server
# RUN flask db upgrade | TODO: Figure out if you can do it in `CMD`

# CMD ["flask", "run", "--port", "80", "--host", "0.0.0.0", "--debug"]
CMD ["flask", "run", "--port", "80", "--host", "0.0.0.0"]