
FROM python:3
RUN pip install globus-compute-endpoint
RUN globus-compute-endpoint configure

# Keeping it alive after starting endpoint
CMD globus-compute-endpoint start default && tail -f /root/.globus_compute/default/endpoint.log