"""Add collection_uuid col to output

Revision ID: 0d628cc4169b
Revises: 7a4e4f6a2834
Create Date: 2024-07-07 16:02:08.109252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d628cc4169b"
down_revision = "7a4e4f6a2834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_uuid", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.drop_column("collection_uuid")

    # ### end Alembic commands ###
