"""empty message

Revision ID: 29e2a4c8947b
Revises: 328435fe2b7f
Create Date: 2023-07-26 15:59:31.275534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e2a4c8947b'
down_revision = '328435fe2b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_refreshed', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('last_refreshed')

    # ### end Alembic commands ###
