"""empty message

Revision ID: 328435fe2b7f
Revises: c638b228eac5
Create Date: 2023-07-19 21:07:13.490301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328435fe2b7f'
down_revision = 'c638b228eac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encoding', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_file', schema=None) as batch_op:
        batch_op.drop_column('encoding')

    # ### end Alembic commands ###
