"""updated source to accept gcs collection and id

Revision ID: 354a7ed3a6ac
Revises: 5c18dd9e73e7
Create Date: 2024-06-20 22:23:20.824131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "354a7ed3a6ac"
down_revision = "5c18dd9e73e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_uuid", sa.String(), nullable=True))

    with op.batch_alter_table("source_file", schema=None) as batch_op:
        batch_op.drop_column("gcs_uuid")
        batch_op.drop_column("gcs_domain")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_file", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("gcs_domain", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("gcs_uuid", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("collection_uuid")

    # ### end Alembic commands ###
