"""Writing file to disk

Revision ID: 3bfddefbf995
Revises: efd5d46f7a15
Create Date: 2023-08-22 19:43:11.705075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bfddefbf995'
down_revision = 'efd5d46f7a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(), nullable=True))
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
