"""Renaming proxy_id to previous_proxy_id

Revision ID: 5019b8424b3a
Revises: ee9d79814627
Create Date: 2023-06-26 18:55:02.805832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5019b8424b3a'
down_revision = 'ee9d79814627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provenance_derivation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_proxy_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('provenance_derivation_proxy_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'proxy', ['previous_proxy_id'], ['id'])
        batch_op.drop_column('proxy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provenance_derivation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('provenance_derivation_proxy_id_fkey', 'proxy', ['proxy_id'], ['id'])
        batch_op.drop_column('previous_proxy_id')

    # ### end Alembic commands ###
