"""updated source to accept a output gcs collection url

Revision ID: 5c18dd9e73e7
Revises: e6af6fccc99c
Create Date: 2024-06-17 18:36:07.852261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c18dd9e73e7"
down_revision = "e6af6fccc99c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("collection_url")

    # ### end Alembic commands ###
