"""Add description column to output

Revision ID: 7a4e4f6a2834
Revises: c0b7b0fc0d74
Create Date: 2024-07-07 15:13:08.748048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a4e4f6a2834"
down_revision = "c0b7b0fc0d74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
