"""Modified provanence capture DB

Revision ID: 87e4b62c2b7e
Revises: 4e2a3f5f194e
Create Date: 2023-12-11 18:58:57.500304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4b62c2b7e'
down_revision = '4e2a3f5f194e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
