"""Add output versioning

Revision ID: ba24f021ed5a
Revises: 87e4b62c2b7e
Create Date: 2023-12-14 03:53:58.947538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba24f021ed5a"
down_revision = "87e4b62c2b7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "output_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["output.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.drop_column("filename")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    op.drop_table("output_version")
    # ### end Alembic commands ###
