"""changes to the model to meet requirements

Revision ID: c0b7b0fc0d74
Revises: 798a339a9ec1
Create Date: 2024-07-04 18:48:45.435275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0b7b0fc0d74"
down_revision = "798a339a9ec1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proxy")
    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.alter_column(
            "last_executed",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    with op.batch_alter_table("source_version", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_version", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=True,
        )

    with op.batch_alter_table("provenance", schema=None) as batch_op:
        batch_op.alter_column(
            "last_executed",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=True,
        )

    op.create_table(
        "proxy",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("representation", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "source_version_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_version.id"],
            name="proxy_source_version_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="proxy_pkey"),
    )
    # ### end Alembic commands ###
