"""Source_file_blob

Revision ID: c638b228eac5
Revises: 5019b8424b3a
Create Date: 2023-07-18 21:19:21.462481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c638b228eac5'
down_revision = '5019b8424b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('source_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_file')
    # ### end Alembic commands ###
