"""Adding id to source_tag

Revision ID: f7cce118e24f
Revises: b95dbe8c0812
Create Date: 2023-06-26 17:33:51.527649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cce118e24f'
down_revision = 'b95dbe8c0812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_tag', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
